python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=3 \
--epoch=0 \
--folder=002_sim_M3_1D_bigger \
--loadModel=1 \
--model=11 \
--normalized=1 \
--objective=2 \
--processingmode=0 \
--spatialDimension=1 \
--training=3 \
--verbosity=1 \
--networkwidth=20 \
--networkdepth=10