python callNeuralClosure.py \
  --alphasampling=1 \
  --batch=128 \
  --curriculum=1 \
  --degree=1 \
  --epoch=1000 \
  --folder=0_data_scaled \
  --loadModel=0 \
  --model=11 \
  --normalized=1 \
  --objective=1 \
  --processingmode=0 \
  --spatialDimension=1 \
  --training=1 \
  --verbosity=1 \
  --networkwidth=49 \
  --networkdepth=12
