python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=2 \
--epoch=1000 \
--folder=002_sim_M2_1D_bigger \
--loadModel=1 \
--model=11 \
--normalized=1 \
--objective=2 \
--processingmode=1 \
--spatialDimension=1 \
--training=1 \
--verbosity=2 \
--networkwidth=15 \
--networkdepth=7