python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=1 \
--epoch=2 \
--folder=00_comp_study/02_M1_1D_MK11_W20 \
--loadModel=1 \
--model=11 \
--normalized=1 \
--objective=1 \
--processingmode=1 \
--spatialDimension=1 \
--training=1 \
--verbosity=1 \
--networkwidth=20 \
--networkdepth=5