python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=3 \
--epoch=1000 \
--folder=002_sim_M3_1D \
--loadModel=1 \
--model=13 \
--normalized=1 \
--objective=1 \
--processingmode=1 \
--spatialDimension=1 \
--training=1 \
--verbosity=1 \
--networkwidth=20 \
--networkdepth=7