python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=1 \
--epoch=100 \
--folder=00_comp_study/01_M1_1D_MK11_W10 \
--loadModel=1 \
--model=11 \
--normalized=1 \
--objective=2 \
--processingmode=1 \
--spatialDimension=1 \
--training=2 \
--verbosity=1 \
--networkwidth=10 \
--networkdepth=10