python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=1 \
--epoch=2 \
--folder=01_comp_study_hAlpha/01_M1_1D_MK11_W10 \
--loadModel=0 \
--model=11 \
--normalized=1 \
--objective=1 \
--processingmode=0 \
--spatialDimension=1 \
--training=1 \
--verbosity=1 \
--networkwidth=10 \
--networkdepth=5

python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=1 \
--epoch=2 \
--folder=01_comp_study_hAlpha/02_M1_1D_MK11_W20 \
--loadModel=0 \
--model=11 \
--normalized=1 \
--objective=1 \
--processingmode=0 \
--spatialDimension=1 \
--training=1 \
--verbosity=1 \
--networkwidth=20 \
--networkdepth=5

python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=1 \
--epoch=10000 \
--folder=01_comp_study_hAlpha/03_M1_1D_MK11_W30 \
--loadModel=0 \
--model=11 \
--normalized=1 \
--objective=1 \
--processingmode=0 \
--spatialDimension=1 \
--training=1 \
--verbosity=1 \
--networkwidth=30 \
--networkdepth=5

python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=1 \
--epoch=2 \
--folder=01_comp_study_hAlpha/04_M1_1D_MK11_W40 \
--loadModel=0 \
--model=11 \
--normalized=1 \
--objective=1 \
--processingmode=0 \
--spatialDimension=1 \
--training=1 \
--verbosity=1 \
--networkwidth=40 \
--networkdepth=5
