python callNeuralClosure.py \
  --alphasampling=0 \
  --batch=128 \
  --curriculum=1 \
  --degree=1 \
  --epoch=2 \
  --folder=test_KL_div \
  --loadModel=0 \
  --model=11 \
  --normalized=1 \
  --objective=3 \
  --processingmode=1 \
  --spatialDimension=1 \
  --training=1 \
  --verbosity=1 \
  --networkwidth=20 \
  --networkdepth=10
