python callNeuralClosure.py \
--alphasampling=0 \
--batch=128 \
--curriculum=1 \
--degree=1 \
--epoch=10000 \
--folder=001_u \
--loadModel=1 \
--model=11 \
--normalized=1 \
--objective=2 \
--processingmode=0 \
--spatialDimension=1 \
--training=1 \
--verbosity=1 \
--networkwidth=15 \
--networkdepth=7